name: Update Contributors in README

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1' # Runs weekly on Monday at midnight

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository to the runner  
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Fetch contributors data using GitHub API
      - name: Fetch Contributors
        run: |
          curl -s https://api.github.com/repos/masterfabric-mobile/swift_camp/contributors | jq 'map(select(.login != "actions-user"))' > contributors.json

      # Step 3: Generate the contributors table
      - name: Generate Contributors Table
        run: |
          echo '<table style="width: 100%; text-align: center; border-spacing: 10px;">' > contributors.md
          jq -r 'to_entries | .[] | 
                 if (.key % 5 == 0) then "<tr>" else "" end +
                 "<td style=\"width: 150px; height: 150px; text-align: center; vertical-align: top;\">" +
                 "<a href=\"" + .value.html_url + "\" style=\"text-decoration: none; color: inherit;\">" +
                 "<div style=\"width: 120px; height: 120px; border-radius: 50%; overflow: hidden; margin: 0 auto;\">" +
                 "<img src=\"" + .value.avatar_url + "\" style=\"width: 100%; height: 100%; object-fit: cover;\" alt=\"" + .value.login + "\" />" +
                 "</div>" +
                 "<br /><sub style=\"word-wrap: break-word; font-size: 14px; max-width: 120px; display: block;\"><b>" + .value.login + "</b></sub></a></td>" +
                 if (.key % 5 == 4) then "</tr>" else "" end' contributors.json >> contributors.md
          echo '</table>' >> contributors.md

      # Step 4: Update the README.md file with the new contributors section
      - name: Update README.md
        run: |
          sed -n '1,/## âœ¨ Contributors/ p' README.md > temp_readme_top.md
          sed -n '/## ðŸ§‘ðŸ»â€ðŸ’» Trainer/,$p' README.md > temp_readme_bottom.md
          cat temp_readme_top.md > new_readme.md
          cat contributors.md >> new_readme.md
          echo '' >> new_readme.md
          echo '## ðŸ§‘ðŸ»â€ðŸ’» Trainer' >> new_readme.md
          sed -n '/## ðŸ§‘ðŸ»â€ðŸ’» Trainer/,$p' temp_readme_bottom.md | tail -n +2 >> new_readme.md
          mv new_readme.md README.md

      # Step 5: Commit and Push Changes
      - name: Commit and Push Changes
        run: |
          # Customize commit user name and email
          git config --local user.name "swift_camp_bot"
          git config --local user.email "bot@swiftcamp.com"
          
          # Add and commit changes
          git add -A
          git commit -m "update: contributors section in README" || echo "No changes to commit"
          
          # Push changes
          git push
